### ISSUE TITLE
Should this be working?

### ISSUE THREAD

**Issue by viziionary** [tariqporter/Gdip#3]
I found an example using your library to get screen capture data, but while it seems to follow all of your function calls correctly, I couldn't figure out why it isn't working. 

Could you try running the code and verify that either I'm using the library incorrectly or the library isn't working as expected?

Code here:

https://autohotkey.com/board/topic/91585-screen-capture-using-only-ahk-no-3rd-party-software-required/

I'm triggering

    pBitmap := Gdip_BitmapFromScreen()
    saveFileTo := folderPath fileName                   
    Gdip_SaveBitmapToFile(pBitmap, saveFileTo)
    Gdip_DisposeImage(pBitmap)

but no image file is being saved. I don't understand what's not working, I even added debug logging into your functions to ensure they're all executing as expected, and making sure there weren't errors, like this all outputs expected results:

    Sysget, x, 76
    Sysget, y, 77	
    Sysget, w, 78
    Sysget, h, 79
    FileAppend, % "Debug - x: " . x . ", y: " . y . ", w: " . w . ", h: " . h . "`n", Log.txt
 
And all the relevant functions are being triggered (in order of execution: `Gdip_Startup`, `Gdip_BitmapFromScreen`, `CreateCompatibleDC`, `CreateDIBSection`, `Gdip_CreateBitmapFromHBITMAP`, `Gdip_SaveBitmapToFile`). But in the end, no file is saved. So really no idea why it isn't working. I do have Gdip dlls on my system lol... (windows 10). And I have tried running as admin. So not sure what else to do to make it work. Hopefully you can help. 

What I'm trying to ultimately do after I get this example code working is loop trough the pixel data of a small region of the screen rather than actually save it to a file, so if you could do me a favor and advise how I would access the actual pixel data rather than format it as an image, that'd be greatly appreciated.

**Comment by viziionary** [comment]
After hours of wasted time I found out that I needed to install the ANSI 32 bit version of AHk for this to work :-: Please add this info to the readme to save time for people who visit this repo with the same problem.

**Comment by tariqporter** [comment]
Hi @viziionary 

Also see the front page of the Gdip thread for a link to `Gdip_All` which will work on current version

https://autohotkey.com/boards/viewtopic.php?f=6&t=6517

I will hopefully have the first public release of Gdip2 in the next few weeks though, which would be a better library to use
